//! Build and export (Ch.27 targets, Ch.38 §38.5 `NOTICES`, §38.7 engine attribution, E-64).
//!
//! [`Packager`] is the trait the HAL exporters (M8) implement. Every product credits Forge
//! Engine in four places, and the packager is what makes the first three automatic
//! ([`Attribution`]): a credits entry, **executable metadata** (Windows `VERSIONINFO`, a Linux
//! ELF `.note.forge` section, a `forge.json` beside the binary) and `NOTICES`; the fourth,
//! the store page, is the licensee's. The credit is static text and metadata — **inert**: no
//! network, no reporting, nothing that executes (I21).
//!
//! [`MemoryPackager`] is the labelled in-memory implementation (D-4): it produces the real
//! attribution, `forge.json`, credits entry and `NOTICES` for a target, and lists the files
//! a package would hold — the executable itself is `UNBUILT` until the exporters exist, and
//! nothing is written to disk.

use serde::{Deserialize, Serialize};

use crate::ProjectError;
use crate::format::ENGINE_VERSION;

/// The engine's `NOTICES` (generated by `just notices`, Ch.38 §38.5): what a distribution
/// carries for the engine's own dependencies.
pub const ENGINE_NOTICES: &str = include_str!("../../../NOTICES");

/// A build target (Ch.27).
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub enum Target {
    Windows,
    Linux,
    Web,
    Android,
}

/// How far a target is supported (Ch.27: Windows and Linux; Web and Android best-effort).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Support {
    Supported,
    BestEffort,
}

impl Target {
    pub const ALL: [Target; 4] = [Target::Windows, Target::Linux, Target::Web, Target::Android];

    #[must_use]
    pub fn id(self) -> &'static str {
        match self {
            Target::Windows => "windows",
            Target::Linux => "linux",
            Target::Web => "web",
            Target::Android => "android",
        }
    }
    #[must_use]
    pub fn label(self) -> &'static str {
        match self {
            Target::Windows => "Windows (x86-64)",
            Target::Linux => "Linux (x86-64)",
            Target::Web => "Web (WebGPU)",
            Target::Android => "Android",
        }
    }
    #[must_use]
    pub fn support(self) -> Support {
        match self {
            Target::Windows | Target::Linux => Support::Supported,
            Target::Web | Target::Android => Support::BestEffort,
        }
    }
    #[must_use]
    pub fn from_id(id: &str) -> Option<Target> {
        Self::ALL.into_iter().find(|t| t.id() == id)
    }
    /// Where the executable metadata goes on this target.
    #[must_use]
    pub fn metadata_carrier(self) -> &'static str {
        match self {
            Target::Windows => "VERSIONINFO resource in the .exe",
            Target::Linux => "ELF .note.forge section",
            Target::Web => "forge.json beside the bundle (no executable header)",
            Target::Android => "forge.json in the APK assets",
        }
    }
}

/// What the product is called and its version (from the project settings).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Product {
    pub name: String,
    pub version: String,
    /// The game's GPU mode id, `"single"` or `"multi"` ([`crate::gpu_mode_id`]); `forge.json`
    /// carries it and the runtime reads it at startup.
    #[serde(default = "single")]
    pub gpu_mode: String,
}

fn single() -> String {
    "single".into()
}

/// The engine credit a package carries (E-64, Ch.38 §38.7).
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Attribution {
    /// The in-product credits / about-screen entry the packager adds.
    pub credits: String,
    /// Executable metadata as `(field, value)`, inserted automatically.
    pub metadata: Vec<(String, String)>,
    /// Where on this target the metadata goes.
    pub carrier: String,
    /// `forge.json`, beside the binary.
    pub forge_json: String,
    /// The `NOTICES` line about the engine (the file itself is the full text).
    pub notices: String,
    /// The licensee's part (EULA): the store page or documentation.
    pub store_page: String,
    /// "Made with Forge Engine" splash, on by default (O-34 open).
    pub splash_default_on: bool,
}

/// The attribution for `product` on `target` — pure: the panel previews exactly what the
/// packager will insert.
#[must_use]
pub fn attribution(product: &Product, target: Target) -> Attribution {
    let credit = format!("Made with Forge Engine {ENGINE_VERSION}");
    let forge_json = serde_json::json!({
        "engine": "Forge Engine",
        "engine_version": ENGINE_VERSION,
        "product": product.name,
        "product_version": product.version,
        "target": target.id(),
        "gpu_mode": crate::gpu_mode_id(Some(&product.gpu_mode)),
    });
    Attribution {
        credits: format!("{credit} \u{2014} forge-engine (see NOTICES for third-party licences)"),
        metadata: vec![
            ("ProductName".into(), product.name.clone()),
            ("ProductVersion".into(), product.version.clone()),
            ("Comments".into(), credit.clone()),
            ("ForgeEngineVersion".into(), ENGINE_VERSION.into()),
        ],
        carrier: target.metadata_carrier().into(),
        forge_json: serde_json::to_string_pretty(&forge_json).unwrap_or_default(),
        notices: "NOTICES: Forge Engine and its third-party dependencies, with their licences"
            .into(),
        store_page:
            "Your part (EULA): credit Forge Engine on the store page or in the documentation".into(),
        splash_default_on: true,
    }
}

/// The first `lines` lines of the `NOTICES` a package ships, plus how many lines it has.
#[must_use]
pub fn notices_preview(lines: usize) -> (String, usize) {
    let total = ENGINE_NOTICES.lines().count();
    let head: Vec<&str> = ENGINE_NOTICES.lines().take(lines).collect();
    (head.join("\n"), total)
}

/// One file of a package.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct PackageFile {
    pub path: String,
    pub bytes: u64,
    /// `None`: produced; `Some(why)`: not built (`UNBUILT(why)`).
    pub unbuilt: Option<String>,
}

/// What a build produced.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct BuildReport {
    pub target: Target,
    pub product: Product,
    pub attribution: Attribution,
    pub files: Vec<PackageFile>,
    /// The linker's map of the executable (every object and symbol it linked), kept beside
    /// the package, not in it: what `test_2d_tax_is_zero` reads. `None`: no
    /// executable was linked (the in-memory packager).
    #[serde(default)]
    pub link_map: Option<String>,
    /// The packager that built it, and whether it is the labelled stand-in.
    pub backend: String,
    pub in_memory: bool,
}

/// What builds and exports a project (the HAL exporters, M8).
pub trait Packager: Send {
    /// The packager's name and whether it is the in-memory stand-in (D-4).
    fn backend(&self) -> (String, bool);
    /// Package `product` for `target`. `project_files` are the project's files (path,
    /// bytes) the package embeds.
    fn package(
        &mut self,
        target: Target,
        product: &Product,
        project_files: &[(String, u64)],
    ) -> Result<BuildReport, ProjectError>;
}

/// The in-memory packager (see the module docs).
#[derive(Debug, Default)]
pub struct MemoryPackager;

impl Packager for MemoryPackager {
    fn backend(&self) -> (String, bool) {
        (
            "in-memory packager (D-4): the attribution, forge.json, credits and NOTICES are real; the executable needs the HAL exporters (M8)".into(),
            true,
        )
    }

    fn package(
        &mut self,
        target: Target,
        product: &Product,
        project_files: &[(String, u64)],
    ) -> Result<BuildReport, ProjectError> {
        if product.name.trim().is_empty() {
            return Err(ProjectError::Build(
                "the product has no name: set the project name first".into(),
            ));
        }
        let a = attribution(product, target);
        let exe = match target {
            Target::Windows => format!("{}.exe", product.name),
            Target::Linux => product.name.clone(),
            Target::Web => "index.html".into(),
            Target::Android => format!("{}.apk", product.name),
        };
        let mut files = vec![
            PackageFile {
                path: exe,
                bytes: 0,
                unbuilt: Some(format!(
                    "the {} exporter (forge-hal, M8) is not built; its metadata will be: {}",
                    target.label(),
                    a.carrier
                )),
            },
            PackageFile {
                path: "forge.json".into(),
                bytes: a.forge_json.len() as u64,
                unbuilt: None,
            },
            PackageFile {
                path: "NOTICES".into(),
                bytes: ENGINE_NOTICES.len() as u64,
                unbuilt: None,
            },
            PackageFile {
                path: "credits.txt".into(),
                bytes: a.credits.len() as u64,
                unbuilt: None,
            },
        ];
        files.extend(project_files.iter().map(|(p, n)| PackageFile {
            path: format!("data/{p}"),
            bytes: *n,
            unbuilt: None,
        }));
        let (backend, in_memory) = self.backend();
        Ok(BuildReport {
            target,
            product: product.clone(),
            attribution: a,
            files,
            backend,
            in_memory,
            link_map: None,
        })
    }
}

/// The exporter for a game built from source with cargo (WP-U16): a real package for the
/// host's desktop target (Windows on Windows, Linux on Linux; cross-target export is the
/// HAL exporters', M8). It builds the game crate's binary in `release` with the requested
/// features, asks the linker for a map of what it linked, and writes the package folder:
/// the executable named after the product, `forge.json`, `NOTICES`, `credits.txt` and the
/// project's data files. The link map is kept beside the package (`BuildReport::link_map`)
/// for the guards that read what a shipped binary contains.
///
/// Not yet: the executable metadata (Windows `VERSIONINFO`, the ELF `.note.forge` section)
/// is the attribution step of M5-27 (`test_attribution_emitted`); the report lists it as
/// unbuilt until then. Nothing here touches the network: cargo runs `--offline --locked`
/// against the lock file and the local registry cache.
#[derive(Clone, Debug)]
pub struct CargoPackager {
    /// The workspace root (where `Cargo.lock` is).
    pub workspace: std::path::PathBuf,
    /// The game crate and its binary.
    pub package: String,
    pub bin: String,
    /// Cargo features for the build (`--features`), and whether the crate's defaults are off.
    pub features: Vec<String>,
    pub no_default_features: bool,
    /// The build's own target directory (an export never shares the developer's).
    pub target_dir: std::path::PathBuf,
    /// Where the package folder is written (created; existing files are overwritten).
    pub out_dir: std::path::PathBuf,
    /// The project's files are copied from here (`None`: they are listed but not copied).
    pub data_root: Option<std::path::PathBuf>,
    /// The cargo to run (`$CARGO` under a cargo build, else `cargo`).
    pub cargo: std::path::PathBuf,
}

impl CargoPackager {
    /// Export `bin` of `package` in `workspace`, building in `target_dir`, into `out_dir`.
    #[must_use]
    pub fn new(
        workspace: impl Into<std::path::PathBuf>,
        package: &str,
        bin: &str,
        target_dir: impl Into<std::path::PathBuf>,
        out_dir: impl Into<std::path::PathBuf>,
    ) -> Self {
        Self {
            workspace: workspace.into(),
            package: package.into(),
            bin: bin.into(),
            features: Vec::new(),
            no_default_features: false,
            target_dir: target_dir.into(),
            out_dir: out_dir.into(),
            data_root: None,
            cargo: std::env::var_os("CARGO").map_or_else(|| "cargo".into(), Into::into),
        }
    }

    /// The desktop target this machine exports (`None`: neither Windows nor Linux).
    #[must_use]
    pub fn host_target() -> Option<Target> {
        if cfg!(windows) {
            Some(Target::Windows)
        } else if cfg!(target_os = "linux") {
            Some(Target::Linux)
        } else {
            None
        }
    }

    fn exe_name(product: &Product, target: Target) -> String {
        let stem: String = product
            .name
            .chars()
            .map(|c| {
                if c.is_alphanumeric() || c == '-' || c == '_' {
                    c
                } else {
                    '-'
                }
            })
            .collect();
        match target {
            Target::Windows => format!("{stem}.exe"),
            _ => stem,
        }
    }

    fn build(&self, map: &std::path::Path) -> Result<std::path::PathBuf, ProjectError> {
        let mut cmd = std::process::Command::new(&self.cargo);
        cmd.current_dir(&self.workspace)
            .env("CARGO_TARGET_DIR", &self.target_dir)
            // A shipped binary carries no debug symbols (smaller download, nothing to leak).
            .args(["--config", "profile.release.strip=\"symbols\""])
            .args(["rustc", "--release", "--locked", "--offline", "-p"])
            .arg(&self.package)
            .arg("--bin")
            .arg(&self.bin);
        if self.no_default_features {
            cmd.arg("--no-default-features");
        }
        if !self.features.is_empty() {
            cmd.arg("--features").arg(self.features.join(","));
        }
        // The linker's map of the final binary only (the dependencies build as usual).
        let flag = if cfg!(windows) {
            format!("/MAP:{}", map.display())
        } else {
            format!("-Wl,-Map={}", map.display())
        };
        cmd.arg("--").arg("-C").arg(format!("link-arg={flag}"));
        let out = cmd
            .output()
            .map_err(|e| ProjectError::Build(format!("cannot run cargo: {e}")))?;
        if !out.status.success() {
            let err = String::from_utf8_lossy(&out.stderr);
            let mut tail: Vec<&str> = err.lines().rev().take(30).collect();
            tail.reverse();
            return Err(ProjectError::Build(format!(
                "cargo rustc -p {} --bin {} failed:\n{}",
                self.package,
                self.bin,
                tail.join("\n")
            )));
        }
        let exe = self.target_dir.join("release").join(format!(
            "{}{}",
            self.bin,
            std::env::consts::EXE_SUFFIX
        ));
        if !exe.is_file() {
            return Err(ProjectError::Build(format!(
                "cargo reported success but {} is not there",
                exe.display()
            )));
        }
        Ok(exe)
    }
}

impl Packager for CargoPackager {
    fn backend(&self) -> (String, bool) {
        (
            format!(
                "cargo exporter: {} built from source in release for this machine's target",
                self.package
            ),
            false,
        )
    }

    fn package(
        &mut self,
        target: Target,
        product: &Product,
        project_files: &[(String, u64)],
    ) -> Result<BuildReport, ProjectError> {
        if product.name.trim().is_empty() {
            return Err(ProjectError::Build(
                "the product has no name: set the project name first".into(),
            ));
        }
        if Self::host_target() != Some(target) {
            return Err(ProjectError::Build(format!(
                "the cargo exporter builds for this machine only; {} needs the HAL exporter (M8)",
                target.label()
            )));
        }
        let io = |what: &str, e: std::io::Error| ProjectError::Build(format!("{what}: {e}"));
        std::fs::create_dir_all(&self.out_dir).map_err(|e| io("the package folder", e))?;
        let maps = self.target_dir.join("link-maps");
        std::fs::create_dir_all(&maps).map_err(|e| io("the link-map folder", e))?;
        // One map per feature set: two exports of one crate never read each other's map.
        let variant = if self.features.is_empty() {
            "default".to_string()
        } else {
            self.features.join("+")
        };
        let map = maps.join(format!("{}.{variant}.map", self.bin));
        let built = self.build(&map)?;
        let a = attribution(product, target);
        let exe_name = Self::exe_name(product, target);
        let exe_bytes = std::fs::copy(&built, self.out_dir.join(&exe_name))
            .map_err(|e| io("copying the executable", e))?;
        let mut files = vec![PackageFile {
            path: exe_name,
            bytes: exe_bytes,
            unbuilt: None,
        }];
        for (name, body) in [
            ("forge.json", a.forge_json.as_str()),
            ("NOTICES", ENGINE_NOTICES),
            ("credits.txt", a.credits.as_str()),
        ] {
            std::fs::write(self.out_dir.join(name), body).map_err(|e| io(name, e))?;
            files.push(PackageFile {
                path: name.into(),
                bytes: body.len() as u64,
                unbuilt: None,
            });
        }
        files.push(PackageFile {
            path: format!("(executable metadata: {})", a.carrier),
            bytes: 0,
            unbuilt: Some(
                "inserted by the attribution step (M5-27, test_attribution_emitted); forge.json carries it today"
                    .into(),
            ),
        });
        for (p, n) in project_files {
            let rel = format!("data/{p}");
            if let Some(root) = &self.data_root {
                let dst = self.out_dir.join(&rel);
                if let Some(parent) = dst.parent() {
                    std::fs::create_dir_all(parent).map_err(|e| io(&rel, e))?;
                }
                std::fs::copy(root.join(p), &dst).map_err(|e| io(&rel, e))?;
            }
            files.push(PackageFile {
                path: rel,
                bytes: *n,
                unbuilt: None,
            });
        }
        let (backend, in_memory) = self.backend();
        Ok(BuildReport {
            target,
            product: product.clone(),
            attribution: a,
            files,
            backend,
            in_memory,
            link_map: Some(map.display().to_string()),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_target_carries_the_credit_in_its_metadata_forge_json_and_notices() {
        let p = Product {
            name: "Skyfall".into(),
            version: "1.2.0".into(),
            gpu_mode: "multi".into(),
        };
        for t in Target::ALL {
            let a = attribution(&p, t);
            assert!(a.credits.contains("Made with Forge Engine"));
            assert!(
                a.metadata
                    .iter()
                    .any(|(k, v)| k == "Comments" && v.contains("Forge Engine"))
            );
            let j: serde_json::Value =
                serde_json::from_str(&a.forge_json).unwrap_or_else(|e| panic!("{e}"));
            assert_eq!(j["engine"], "Forge Engine");
            assert_eq!(j["product"], "Skyfall");
            assert_eq!(j["gpu_mode"], "multi");
            let r = MemoryPackager
                .package(t, &p, &[("project/scene.ron".into(), 10)])
                .unwrap_or_else(|e| panic!("{e}"));
            let names: Vec<&str> = r.files.iter().map(|f| f.path.as_str()).collect();
            for f in [
                "forge.json",
                "NOTICES",
                "credits.txt",
                "data/project/scene.ron",
            ] {
                assert!(names.contains(&f), "{t:?}: {names:?}");
            }
            assert!(r.files[0].unbuilt.is_some(), "the executable is UNBUILT");
            assert!(r.in_memory);
        }
        let (head, total) = notices_preview(5);
        assert!(head.starts_with("FORGE ENGINE"));
        assert!(total > 5);
        assert!(
            MemoryPackager
                .package(
                    Target::Linux,
                    &Product {
                        name: " ".into(),
                        version: "1".into(),
                        gpu_mode: "single".into(),
                    },
                    &[]
                )
                .is_err()
        );
    }
}
