//! `cargo xtask premium-boundary` — the open-core boundary holds (ADR 0059, E-66).
//!
//! Over every workspace member and every repository file, with `premium.ron` saying what is
//! premium:
//!
//! * **P1.** A base member never depends on a premium crate — in `[dependencies]`,
//!   `[dev-dependencies]` or `[build-dependencies]`, any target. Otherwise the export could
//!   not build it.
//! * **P2.** A base file never names a premium identifier (a premium crate name in either
//!   spelling, a premium path, a listed type/module/tool name, or a premium DoD id, gate row
//!   or error code, a range citation spanning one included), in its path or its text.
//!   Checked on what the export would write: `tests/gates.ron` without its premium rows and
//!   the workspace `Cargo.toml` without its premium tables. Markdown and `dod-status.ron`
//!   are not checked here: the export scrubs them ([`super::scrub`]) and leak-scans the
//!   result. `Cargo.lock` is regenerated by the export.
//! * **P3.** A premium path never sits inside a base member (premium code lodged in a base
//!   crate).
//! * **P4.** A base member never declares a premium cargo feature.
//! * **P5.** `premium.ron` is exact: each premium crate exists under its name, each premium
//!   path exists, each marked doc section is marked exactly once, each premium DoD id, gate
//!   row and error code exists, each rewrite still matches.
//!
//! P1-P3 violations that exist today are **debt**, listed in `premium_debt.ron`, each with the
//! work package that removes it (WP-42, WP-43, WP-44; `premium.ron` says what each moved). The debt list is exact (a listed violation
//! that no longer exists is an error: delete the line), and it **only shrinks**: its size
//! must equal [`DEBT_CEILING`], which may only go down, and never above [`DEBT_AT_WP41`].
//! `cargo xtask premium-boundary --write-debt` rewrites the debt file to what is still true
//! (it never adds an entry once the file exists) and prints the new ceiling.
//!
//! [`DEBT_AT_WP41`] is the baseline drawn by WP-41 and is never raised: a change that raises
//! it (or [`DEBT_CEILING`] above it) grows the debt, which a reviewer rejects.
//!
//! A repository without `premium.ron` (the public export) has nothing premium to separate
//! and says so, unless it still has a debt file or a non-zero ceiling: then the manifest was
//! lost, and the check fails ([`no_manifest`]).

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;

use serde::Deserialize;

use super::{DEBT_FILE, MANIFEST_FILE, MOVING_WPS, Manifest, scrub};
use crate::layering::{self, Kind};
use crate::util::{Failure, XResult, read};

/// The size of `premium_debt.ron` (dependency edges + identifiers named + lodged paths).
/// **Lower it** in the change that burns debt down (the check requires it to equal the debt's
/// size, so it cannot be forgotten). **Never raise it**: a new premium name in a base file is
/// a boundary violation to fix, not debt to record.
///
/// Raised from 558 to 559 by the WP-41 integrate step: `dev` had moved ahead with WP-U20
/// (scene composition, ADR 0058) before this boundary existed there, and one of its guard
/// tests drives the real agent-protocol server, lodged in the base `forge-editor` crate
/// exactly like the other WP-42 items above. This is the one violation WP-U20's code added
/// that a wording fix could not remove (its two other new premium mentions were reworded,
/// and its UI test's agent-issued command swapped for a script-issued one, without touching
/// this test's real agent-protocol integration) — see `premium.ron`'s `paths` entry and
/// `premium_debt.ron`'s `lodged` entry, both under WP-42, for the test file itself.
///
/// Lowered from 559 to 248 by WP-43 (ADR 0060) and WP-42 (ADR 0061) together: the frame
/// stack left the base (every WP-43 entry, and three WP-44 mentions of a premium crate in
/// the text it rewrote), and every WP-42 entry is gone (the base crates' dependency edges,
/// the names and the lodged test). Only WP-44 debt remains.
///
/// Lowered from 248 to 0 by WP-44 (ADR 0062): the last premium items left the base, and no
/// base file names a premium identifier or a code term (`premium.ron`'s `code_terms`, which
/// catch premium text a rename would hide). The debt is empty: every boundary violation from
/// now on is an error to fix, never debt.
pub const DEBT_CEILING: usize = 0;

/// The debt when the boundary was drawn (WP-41). [`DEBT_CEILING`] never exceeds it.
///
/// Raised from 558 to 559 alongside `DEBT_CEILING` for the same reason (WP-41 integrate
/// step, WP-U20's one new unavoidable violation) — see `DEBT_CEILING`.
pub const DEBT_AT_WP41: usize = 559;

pub const GATES_FILE: &str = "tests/gates.ron";
pub const STATUS_FILE: &str = "docs/plan/dod-status.ron";
pub const MILESTONES_FILE: &str = "docs/plan/milestones.md";
pub const ERROR_CODES_FILE: &str = "docs/error-codes.md";

/// `premium_debt.ron`.
#[derive(Debug, Clone, Default, Deserialize, PartialEq, Eq)]
pub struct Debt {
    #[serde(default)]
    pub deps: Vec<DepDebt>,
    #[serde(default)]
    pub names: Vec<NameDebt>,
    #[serde(default)]
    pub lodged: Vec<LodgedDebt>,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct DepDebt {
    pub krate: String,
    pub on: String,
    pub wp: String,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct NameDebt {
    pub path: String,
    pub wp: String,
    pub identifiers: Vec<String>,
}

#[derive(Debug, Clone, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct LodgedDebt {
    pub path: String,
    pub wp: String,
}

impl Debt {
    pub fn parse(src: &str) -> XResult<Self> {
        ron::from_str(src).map_err(|e| Failure::one(format!("{DEBT_FILE}: parse error: {e}")))
    }

    /// The debt's size: dependency edges + identifiers named + lodged paths.
    pub fn size(&self) -> usize {
        self.deps.len()
            + self
                .names
                .iter()
                .map(|n| n.identifiers.len())
                .sum::<usize>()
            + self.lodged.len()
    }

    pub fn is_empty(&self) -> bool {
        self.size() == 0
    }

    /// Per work package: how much debt it owns.
    pub fn by_wp(&self) -> BTreeMap<String, usize> {
        let mut out = BTreeMap::new();
        for d in &self.deps {
            *out.entry(d.wp.clone()).or_default() += 1;
        }
        for n in &self.names {
            *out.entry(n.wp.clone()).or_default() += n.identifiers.len();
        }
        for l in &self.lodged {
            *out.entry(l.wp.clone()).or_default() += 1;
        }
        out
    }

    /// The RON text of this debt, sorted, one entry per line.
    pub fn render(&self) -> String {
        let mut s = String::from(
            "// premium_debt.ron — known open-core boundary violations (ADR 0059, E-66), each with the\n\
             // work package that removes it. Checked by `cargo xtask premium-boundary`: exact (a\n\
             // violation that is gone must be deleted here) and shrink-only (its size equals\n\
             // xtask/src/premium/boundary.rs DEBT_CEILING, which only goes down). Regenerate with\n\
             // `cargo xtask premium-boundary --write-debt`, which never adds an entry.\n(\n    deps: [\n",
        );
        let mut deps = self.deps.clone();
        deps.sort();
        for d in &deps {
            s.push_str(&format!(
                "        (krate: {:?}, on: {:?}, wp: {:?}),\n",
                d.krate, d.on, d.wp
            ));
        }
        s.push_str("    ],\n    names: [\n");
        let mut names = self.names.clone();
        names.sort();
        for n in &names {
            let ids: Vec<String> = n.identifiers.iter().map(|i| format!("{i:?}")).collect();
            s.push_str(&format!(
                "        (path: {:?}, wp: {:?}, identifiers: [{}]),\n",
                n.path,
                n.wp,
                ids.join(", ")
            ));
        }
        s.push_str("    ],\n    lodged: [\n");
        let mut lodged = self.lodged.clone();
        lodged.sort();
        for l in &lodged {
            s.push_str(&format!("        (path: {:?}, wp: {:?}),\n", l.path, l.wp));
        }
        s.push_str("    ],\n)\n");
        s
    }

    /// Keep only what `current` still has (never adds).
    pub fn intersect(&self, current: &Debt) -> Debt {
        let deps = self
            .deps
            .iter()
            .filter(|d| {
                current
                    .deps
                    .iter()
                    .any(|c| c.krate == d.krate && c.on == d.on)
            })
            .cloned()
            .collect();
        let names = self
            .names
            .iter()
            .filter_map(|n| {
                let now: BTreeSet<&String> = current
                    .names
                    .iter()
                    .filter(|c| c.path == n.path)
                    .flat_map(|c| &c.identifiers)
                    .collect();
                let ids: Vec<String> = n
                    .identifiers
                    .iter()
                    .filter(|i| now.contains(i))
                    .cloned()
                    .collect();
                (!ids.is_empty()).then(|| NameDebt {
                    path: n.path.clone(),
                    wp: n.wp.clone(),
                    identifiers: ids,
                })
            })
            .collect();
        let lodged = self
            .lodged
            .iter()
            .filter(|l| current.lodged.iter().any(|c| c.path == l.path))
            .cloned()
            .collect();
        Debt {
            deps,
            names,
            lodged,
        }
    }
}

/// One workspace member, as the boundary sees it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MemberInfo {
    pub name: String,
    /// Repo-relative directory.
    pub dir: String,
    pub deps: Vec<(String, Kind)>,
    pub features: Vec<String>,
}

/// The repository, as the boundary sees it.
#[derive(Debug, Clone, Default)]
pub struct Repo {
    pub members: Vec<MemberInfo>,
    /// Base files to scan for identifiers: `(repo path, text the export would write)`.
    pub files: Vec<(String, String)>,
    /// Every repository file path.
    pub paths: BTreeSet<String>,
    /// Markdown texts (for the section markers) and the milestone/gate ids present.
    pub docs: BTreeMap<String, String>,
    pub dod_ids: BTreeSet<String>,
    pub gate_ids: BTreeSet<String>,
}

/// The WP that owns an identifier (for new debt entries).
fn identifier_wp(m: &Manifest, id: &str) -> String {
    if let Some(wp) = m.id_wp(id) {
        return wp.to_string();
    }
    if let Some(i) = m.identifiers.iter().find(|i| i.text == id) {
        return i.wp.clone();
    }
    if let Some(p) = m
        .paths
        .iter()
        .find(|p| p.path == id && p.wp != super::PRIVATE)
    {
        return p.wp.clone();
    }
    if let Some(c) = m
        .crates
        .iter()
        .find(|c| c.name == id || c.name.replace('-', "_") == id || c.path == id)
    {
        return c.wp.clone();
    }
    "WP-44".to_string()
}

/// Every P1-P3 violation in `repo`, as debt entries.
pub fn violations(m: &Manifest, repo: &Repo) -> Debt {
    let mut debt = Debt::default();
    let base = |name: &str| !m.is_premium_crate(name);
    for mem in repo.members.iter().filter(|x| base(&x.name)) {
        let mut seen = BTreeSet::new();
        for (dep, _) in &mem.deps {
            if m.is_premium_crate(dep) && seen.insert(dep.clone()) {
                let wp = m
                    .crates
                    .iter()
                    .find(|c| &c.name == dep)
                    .map_or("WP-44".to_string(), |c| c.wp.clone());
                debt.deps.push(DepDebt {
                    krate: mem.name.clone(),
                    on: dep.clone(),
                    wp,
                });
            }
        }
    }
    let matcher = m.code_matcher();
    for (path, text) in &repo.files {
        let mut hits = matcher.all_hits(path);
        hits.extend(matcher.all_hits(text));
        let mut by_wp: BTreeMap<String, Vec<String>> = BTreeMap::new();
        for h in hits {
            by_wp.entry(identifier_wp(m, &h)).or_default().push(h);
        }
        for (wp, identifiers) in by_wp {
            debt.names.push(NameDebt {
                path: path.clone(),
                wp,
                identifiers,
            });
        }
    }
    for p in &m.paths {
        let inside_base = repo
            .members
            .iter()
            .filter(|x| base(&x.name))
            .any(|x| p.path.starts_with(&format!("{}/", x.dir)));
        let present = repo
            .paths
            .iter()
            .any(|f| f == &p.path || f.starts_with(&format!("{}/", p.path)));
        if inside_base && present {
            debt.lodged.push(LodgedDebt {
                path: p.path.clone(),
                wp: p.wp.clone(),
            });
        }
    }
    debt
}

/// P5: the manifest agrees with the repository.
pub fn manifest_errors(m: &Manifest, repo: &Repo) -> Vec<String> {
    let mut errs = m.validate();
    for c in &m.crates {
        match repo.members.iter().find(|x| x.dir == c.path) {
            Some(x) if x.name == c.name => {}
            Some(x) => errs.push(format!(
                "{MANIFEST_FILE}: crate {} at {} is named {} (P5)",
                c.name, c.path, x.name
            )),
            None => errs.push(format!(
                "{MANIFEST_FILE}: crate {} lists {}, which is not a workspace member (P5)",
                c.name, c.path
            )),
        }
    }
    for p in &m.paths {
        let present = repo
            .paths
            .iter()
            .any(|f| f == &p.path || f.starts_with(&format!("{}/", p.path)));
        if !present {
            errs.push(format!(
                "{MANIFEST_FILE}: premium path {} does not exist (P5): it moved or went; update the entry",
                p.path
            ));
        }
    }
    for b in &m.nextest_binaries {
        let premium_file = repo.paths.iter().any(|f| {
            f.ends_with(&format!("/{b}.rs"))
                && m.crates
                    .iter()
                    .any(|c| f.starts_with(&format!("{}/", c.path)))
        });
        if !premium_file {
            errs.push(format!(
                "{MANIFEST_FILE}: nextest binary {b} is no test file of a premium crate (P5): update the entry"
            ));
        }
    }
    for w in &m.withheld {
        if !repo.paths.contains(&w.path) {
            errs.push(format!(
                "{MANIFEST_FILE}: withheld file {} does not exist (P5): update the entry",
                w.path
            ));
        }
    }
    for f in &m.features {
        if let Some(x) = repo
            .members
            .iter()
            .find(|x| x.name == f.krate && !m.is_premium_crate(&x.name))
            && x.features.contains(&f.feature)
        {
            errs.push(format!(
                "{}/Cargo.toml: base crate {} declares premium feature `{}` (P4): {}",
                x.dir, x.name, f.feature, f.why
            ));
        }
    }
    // Section markers: every marked file's markers are all listed and each listed one found.
    let mut listed: BTreeMap<&str, BTreeSet<String>> = BTreeMap::new();
    for s in &m.doc_sections {
        listed
            .entry(s.file.as_str())
            .or_default()
            .insert(s.id.clone());
    }
    for (file, text) in &repo.docs {
        let known = listed.get(file.as_str()).cloned().unwrap_or_default();
        match scrub::cut_marked(text, &known) {
            Err(e) => errs.push(format!("{file}: {e} (P5)")),
            Ok((_, found)) => {
                let found: BTreeSet<String> = found.into_iter().collect();
                if found.len() != known.len() {
                    for id in known.difference(&found) {
                        errs.push(format!(
                            "{MANIFEST_FILE}: doc section {id} is not marked in {file} (P5)"
                        ));
                    }
                }
            }
        }
    }
    for (file, _) in listed {
        if !repo.docs.contains_key(file) {
            errs.push(format!(
                "{MANIFEST_FILE}: doc sections name {file}, which does not exist (P5)"
            ));
        }
    }
    for id in &m.dod_list() {
        if !repo.dod_ids.contains(id) {
            errs.push(format!(
                "{MANIFEST_FILE}: premium DoD id {id} is not in {MILESTONES_FILE} (P5)"
            ));
        }
    }
    for id in &m.gate_list() {
        if !repo.gate_ids.contains(id) {
            errs.push(format!(
                "{MANIFEST_FILE}: premium gate row {id} is not in {GATES_FILE} (P5)"
            ));
        }
    }
    let codes = repo
        .docs
        .get(ERROR_CODES_FILE)
        .map(String::as_str)
        .unwrap_or("");
    for id in &m.error_code_list() {
        if !codes.contains(&format!("| {id} |")) {
            errs.push(format!(
                "{MANIFEST_FILE}: premium error code {id} is not a row of {ERROR_CODES_FILE} (P5)"
            ));
        }
    }
    for r in &m.rewrites {
        match repo.docs.get(&r.file) {
            Some(t) if t.contains(&r.from) => {}
            _ => errs.push(format!(
                "{MANIFEST_FILE}: rewrite in {} no longer matches {:?} (P5)",
                r.file, r.from
            )),
        }
    }
    errs
}

/// Compare the repository's violations with the recorded debt.
pub fn check(m: &Manifest, debt: &Debt, repo: &Repo, ceiling: usize) -> Vec<String> {
    let mut errs = manifest_errors(m, repo);
    let now = violations(m, repo);
    for d in &now.deps {
        if !debt.deps.iter().any(|x| x.krate == d.krate && x.on == d.on) {
            errs.push(format!(
                "base crate {} depends on premium crate {} (P1): a base crate must build without the premium ones — move the code that needs it into a premium crate or plugin",
                d.krate, d.on
            ));
        }
    }
    for x in &debt.deps {
        if !now.deps.iter().any(|d| x.krate == d.krate && x.on == d.on) {
            errs.push(format!(
                "{DEBT_FILE}: {} no longer depends on {}: delete the entry (the debt only shrinks)",
                x.krate, x.on
            ));
        }
    }
    for n in &now.names {
        let listed: BTreeSet<&String> = debt
            .names
            .iter()
            .filter(|x| x.path == n.path)
            .flat_map(|x| &x.identifiers)
            .collect();
        for id in &n.identifiers {
            if !listed.contains(id) {
                errs.push(format!(
                    "{}: names premium identifier `{id}` (P2): the public export may not contain it — move this code to the premium side or rename it",
                    n.path
                ));
            }
        }
    }
    for x in &debt.names {
        let now_ids: BTreeSet<&String> = now
            .names
            .iter()
            .filter(|n| n.path == x.path)
            .flat_map(|n| &n.identifiers)
            .collect();
        for id in &x.identifiers {
            if !now_ids.contains(id) {
                errs.push(format!(
                    "{DEBT_FILE}: {} no longer names `{id}`: delete it from the entry (the debt only shrinks)",
                    x.path
                ));
            }
        }
    }
    for l in &now.lodged {
        if !debt.lodged.iter().any(|x| x.path == l.path) {
            errs.push(format!(
                "{}: premium code lodged in a base crate (P3): move it into a premium crate",
                l.path
            ));
        }
    }
    for x in &debt.lodged {
        if !now.lodged.iter().any(|l| l.path == x.path) {
            errs.push(format!(
                "{DEBT_FILE}: {} is no longer lodged in a base crate: delete the entry",
                x.path
            ));
        }
    }
    let wps = debt
        .deps
        .iter()
        .map(|d| (&d.wp, format!("{} -> {}", d.krate, d.on)))
        .chain(debt.names.iter().map(|n| (&n.wp, n.path.clone())))
        .chain(debt.lodged.iter().map(|l| (&l.wp, l.path.clone())));
    for (wp, what) in wps {
        if !MOVING_WPS.contains(&wp.as_str()) {
            errs.push(format!(
                "{DEBT_FILE}: {what} names {wp}; debt belongs to one of {MOVING_WPS:?}"
            ));
        }
    }
    let size = debt.size();
    if size > ceiling {
        errs.push(format!(
            "{DEBT_FILE}: the debt grew to {size}, above the ceiling {ceiling}: the debt only shrinks — fix the new violation instead of recording it"
        ));
    } else if size < ceiling {
        errs.push(format!(
            "{DEBT_FILE}: the debt shrank to {size}; lower DEBT_CEILING in xtask/src/premium/boundary.rs from {ceiling} to {size} so it cannot grow back"
        ));
    }
    errs
}

fn member_infos(root: &Path) -> XResult<Vec<MemberInfo>> {
    let mut out = Vec::new();
    for mem in layering::members(root)? {
        let dir = mem
            .manifest
            .strip_suffix("/Cargo.toml")
            .unwrap_or(&mem.manifest)
            .to_string();
        let doc: toml::Table = read(&root.join(&mem.manifest))?
            .parse()
            .map_err(|e| Failure::one(format!("{}: {e}", mem.manifest)))?;
        let features = doc
            .get("features")
            .and_then(toml::Value::as_table)
            .map(|t| t.keys().cloned().collect())
            .unwrap_or_default();
        out.push(MemberInfo {
            name: mem.name,
            dir,
            deps: mem.deps.into_iter().map(|(d, _, k)| (d, k)).collect(),
            features,
        });
    }
    Ok(out)
}

/// Is this file checked by P2 (not markdown, not a scrubbed or regenerated file)?
pub fn is_code_checked(m: &Manifest, rel: &str) -> bool {
    !m.excluded(rel) && !rel.ends_with(".md") && rel != STATUS_FILE && rel != "Cargo.lock"
}

/// The nextest configuration (its serial groups name test binaries).
pub const NEXTEST_FILE: &str = ".config/nextest.toml";

/// `text` (a nextest configuration) without the `binary(<name>)` clauses of `binaries` in its
/// filter expressions (the ` | ` joining a dropped clause goes with it).
pub fn strip_nextest_binaries(text: &str, binaries: &[String]) -> String {
    let mut out = text.to_string();
    for b in binaries {
        let clause = format!("binary({b})");
        for (from, to) in [
            (format!(" | {clause}"), String::new()),
            (format!("{clause} | "), String::new()),
        ] {
            out = out.replace(&from, &to);
        }
    }
    out
}

/// The text the export would write for a checked file (`None` for binary files).
pub fn export_text(m: &Manifest, rel: &str, raw: &[u8]) -> Option<String> {
    let text = std::str::from_utf8(raw).ok()?.replace("\r\n", "\n");
    Some(match rel {
        GATES_FILE => {
            let rows: BTreeSet<String> = m.gate_list().into_iter().collect();
            scrub::cut_ron_rows(&text, &|id, _| rows.contains(id)).0
        }
        "Cargo.toml" => {
            let paths: Vec<String> = m.crates.iter().map(|c| c.path.clone()).collect();
            scrub::strip_workspace_manifest(&text, &|n| m.is_premium_crate(n), &paths)
        }
        NEXTEST_FILE => strip_nextest_binaries(&text, &m.nextest_binaries),
        _ => text,
    })
}

/// Read the repository for the boundary check.
pub fn load_repo(root: &Path, m: &Manifest) -> XResult<Repo> {
    let all = crate::plan_coverage::repo_files(root);
    let mut repo = Repo {
        members: member_infos(root)?,
        paths: all.iter().cloned().collect(),
        ..Repo::default()
    };
    for rel in &all {
        if rel.ends_with(".md") {
            if let Ok(t) = read(&root.join(rel)) {
                repo.docs.insert(rel.clone(), t);
            }
            continue;
        }
        if !is_code_checked(m, rel) {
            continue;
        }
        let Ok(raw) = std::fs::read(root.join(rel)) else {
            continue;
        };
        if let Some(t) = export_text(m, rel, &raw) {
            repo.files.push((rel.clone(), t));
        }
    }
    if let Some(ms) = repo.docs.get(MILESTONES_FILE) {
        repo.dod_ids = crate::dod::milestone_ids(ms).into_iter().collect();
    }
    if let Ok(g) = read(&root.join(GATES_FILE)) {
        repo.gate_ids = crate::gate::parse(&g)?
            .rows
            .into_iter()
            .map(|r| r.id)
            .collect();
    }
    Ok(repo)
}

pub fn load_debt(root: &Path) -> XResult<Option<Debt>> {
    let p = root.join(DEBT_FILE);
    if !p.is_file() {
        return Ok(None);
    }
    Debt::parse(&read(&p)?).map(Some)
}

/// A repository without `premium.ron`. The public edition has none, no debt file and a zero
/// ceiling (a code export refuses until the debt is gone). A repository that still has debt
/// or a non-zero ceiling but no manifest lost its manifest: that fails, or deleting the
/// manifest would silently turn the whole check off.
pub fn no_manifest(debt_file: bool, ceiling: usize) -> XResult<String> {
    if debt_file || ceiling > 0 {
        return Err(Failure::one(format!(
            "premium-boundary: no {MANIFEST_FILE}, but {} — the manifest was lost: restore it (the public edition has neither)",
            if debt_file {
                format!("{DEBT_FILE} exists")
            } else {
                format!("DEBT_CEILING is {ceiling}")
            }
        )));
    }
    Ok(format!(
        "premium-boundary: no {MANIFEST_FILE}: this is the public edition, with nothing premium to separate\n"
    ))
}

/// `cargo xtask premium-boundary [--write-debt]`.
pub fn run(root: &Path, write_debt: bool) -> XResult<String> {
    let Some(m) = Manifest::load(root)? else {
        return no_manifest(root.join(DEBT_FILE).is_file(), DEBT_CEILING);
    };
    let repo = load_repo(root, &m)?;
    let existing = load_debt(root)?;
    if write_debt {
        let now = violations(&m, &repo);
        let next = match &existing {
            Some(d) => d.intersect(&now),
            None => now,
        };
        std::fs::write(root.join(DEBT_FILE), next.render())
            .map_err(|e| Failure::one(format!("cannot write {DEBT_FILE}: {e}")))?;
        return Ok(format!(
            "premium-boundary: wrote {DEBT_FILE}: size {} ({:?}); set DEBT_CEILING to {}\n",
            next.size(),
            next.by_wp(),
            next.size()
        ));
    }
    let debt = existing.unwrap_or_default();
    Failure::many(check(&m, &debt, &repo, DEBT_CEILING))?;
    Ok(format!(
        "premium-boundary: {} premium crates, {} premium paths, {} base members, {} base files checked; debt {} of ceiling {} ({:?})\n",
        m.crates.len(),
        m.paths.len(),
        repo.members
            .iter()
            .filter(|x| !m.is_premium_crate(&x.name))
            .count(),
        repo.files.len(),
        debt.size(),
        DEBT_CEILING,
        debt.by_wp()
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest() -> Manifest {
        Manifest::parse(
            r#"(
                crates: [(name: "forge-secret", path: "crates/forge-secret", wp: "WP-42", what: "premium")],
                paths: [(path: "crates/forge-base/src/hidden.rs", wp: "WP-43", why: "lodged")],
                features: [(krate: "forge-base", feature: "secret", why: "premium feature")],
                identifiers: [(text: "HiddenTree", wp: "WP-43")],
            )"#,
        )
        .unwrap_or_else(|e| panic!("{e}"))
    }

    fn member(name: &str, dir: &str, deps: &[(&str, Kind)]) -> MemberInfo {
        MemberInfo {
            name: name.into(),
            dir: dir.into(),
            deps: deps.iter().map(|(d, k)| ((*d).to_string(), *k)).collect(),
            features: Vec::new(),
        }
    }

    /// A faithful repository: one base crate, one premium crate, no violations.
    fn clean_repo() -> Repo {
        Repo {
            members: vec![
                member("forge-base", "crates/forge-base", &[]),
                member(
                    "forge-secret",
                    "crates/forge-secret",
                    &[("forge-base", Kind::Normal)],
                ),
            ],
            files: vec![(
                "crates/forge-base/src/lib.rs".into(),
                "pub fn base() {}".into(),
            )],
            paths: [
                "crates/forge-base/src/lib.rs",
                "crates/forge-secret/src/lib.rs",
            ]
            .iter()
            .map(|s| (*s).to_string())
            .collect(),
            ..Repo::default()
        }
    }

    fn manifest_clean() -> Manifest {
        let mut m = manifest();
        m.paths.clear();
        m
    }

    #[test]
    fn a_clean_repository_passes() {
        let errs = check(&manifest_clean(), &Debt::default(), &clean_repo(), 0);
        assert!(errs.is_empty(), "{errs:#?}");
    }

    #[test]
    fn positive_control_a_base_crate_adding_a_premium_dependency_fails() {
        for kind in [Kind::Normal, Kind::Dev, Kind::Build] {
            let mut repo = clean_repo();
            repo.members[0].deps.push(("forge-secret".into(), kind));
            let errs = check(&manifest_clean(), &Debt::default(), &repo, 0);
            assert!(
                errs.len() == 1
                    && errs[0].contains("forge-base depends on premium crate forge-secret")
                    && errs[0].contains("(P1)"),
                "{kind:?}: {errs:#?}"
            );
        }
    }

    #[test]
    fn positive_control_a_base_file_naming_a_premium_identifier_fails() {
        for text in [
            "use forge_secret::X;",
            "let t: HiddenTree;",
            "// see forge-secret",
        ] {
            let mut repo = clean_repo();
            repo.files[0].1 = text.into();
            let errs = check(&manifest_clean(), &Debt::default(), &repo, 0);
            assert!(
                errs.len() == 1 && errs[0].contains("(P2)"),
                "{text}: {errs:#?}"
            );
        }
    }

    /// Follow-up (a) of WP-44: premium code that names no premium identifier (it was moved
    /// onto a base seam, or renamed) is still caught by what it talks about.
    #[test]
    fn positive_control_a_base_file_talking_about_a_premium_feature_fails() {
        let mut terms = manifest_clean();
        terms.code_terms = vec!["hush".into()];
        for text in [
            "// the Hushed pass runs one tick behind",
            "fn hush_at(t: u64) {}",
            "let e = SystemHush::new();",
        ] {
            let mut repo = clean_repo();
            repo.files[0].1 = text.into();
            let errs = check(&terms, &Debt::default(), &repo, 0);
            assert!(
                errs.len() == 1 && errs[0].contains("(P2)"),
                "{text}: {errs:#?}"
            );
            // The term is what catches it: without it the same file passes.
            let errs = check(&manifest_clean(), &Debt::default(), &repo, 0);
            assert!(errs.is_empty(), "{text}: {errs:#?}");
        }
    }

    #[test]
    fn positive_control_lodged_premium_code_and_premium_features_fail() {
        let mut repo = clean_repo();
        repo.paths.insert("crates/forge-base/src/hidden.rs".into());
        let errs = check(&manifest(), &Debt::default(), &repo, 0);
        assert!(errs.len() == 1 && errs[0].contains("(P3)"), "{errs:#?}");
        let mut repo = clean_repo();
        repo.members[0].features.push("secret".into());
        let errs = check(&manifest_clean(), &Debt::default(), &repo, 0);
        assert!(errs.len() == 1 && errs[0].contains("(P4)"), "{errs:#?}");
    }

    #[test]
    fn debt_covers_known_violations_and_must_be_exact_and_shrink_only() {
        let mut repo = clean_repo();
        repo.members[0]
            .deps
            .push(("forge-secret".into(), Kind::Dev));
        repo.files[0].1 = "HiddenTree forge_secret".into();
        let debt = violations(&manifest_clean(), &repo);
        assert_eq!(debt.size(), 3);
        assert_eq!(debt.by_wp().get("WP-42"), Some(&2));
        assert_eq!(debt.by_wp().get("WP-43"), Some(&1));
        // Recorded debt passes, at its exact ceiling.
        let errs = check(&manifest_clean(), &debt, &repo, 3);
        assert!(errs.is_empty(), "{errs:#?}");
        // The ceiling is exact both ways.
        assert!(check(&manifest_clean(), &debt, &repo, 4)[0].contains("lower DEBT_CEILING"));
        assert!(check(&manifest_clean(), &debt, &repo, 2)[0].contains("above the ceiling"));
        // A violation fixed but still listed is stale.
        let mut fixed = repo.clone();
        fixed.files[0].1 = "forge_secret".into();
        let errs = check(&manifest_clean(), &debt, &fixed, 3);
        assert!(
            errs.iter()
                .any(|e| e.contains("no longer names `HiddenTree`")),
            "{errs:#?}"
        );
        // A new violation is not covered by the old debt.
        let mut worse = repo.clone();
        worse
            .files
            .push(("tools/x/src/main.rs".into(), "forge_secret".into()));
        let errs = check(&manifest_clean(), &debt, &worse, 3);
        assert!(
            errs.iter().any(|e| e.starts_with("tools/x/src/main.rs")),
            "{errs:#?}"
        );
        // --write-debt shrinks and never grows.
        let shrunk = debt.intersect(&violations(&manifest_clean(), &worse));
        assert_eq!(shrunk, debt);
        let shrunk = debt.intersect(&violations(&manifest_clean(), &fixed));
        assert_eq!(shrunk.size(), 2);
        // The rendered file parses back.
        assert_eq!(Debt::parse(&debt.render()).unwrap_or_default(), {
            let mut d = debt.clone();
            d.deps.sort();
            d.names.sort();
            d
        });
    }

    #[test]
    fn debt_entries_must_name_a_moving_wp() {
        let mut repo = clean_repo();
        repo.files[0].1 = "forge_secret".into();
        let mut debt = violations(&manifest_clean(), &repo);
        debt.names[0].wp = "WP-99".into();
        let errs = check(&manifest_clean(), &debt, &repo, 1);
        assert!(errs.iter().any(|e| e.contains("names WP-99")), "{errs:#?}");
    }

    #[test]
    fn the_manifest_must_match_the_repository() {
        let mut m = manifest_clean();
        m.crates[0].path = "crates/nowhere".into();
        m.dod_ids.push(super::super::IdGroup {
            wp: "WP-44".into(),
            ids: vec!["M9-1".into()],
        });
        m.gate_rows.push(super::super::IdGroup {
            wp: "WP-44".into(),
            ids: vec!["C-nowhere".into()],
        });
        m.error_codes.push(super::super::IdGroup {
            wp: "WP-44".into(),
            ids: vec!["NOPE-0001".into()],
        });
        m.doc_sections.push(super::super::DocSection {
            file: "docs/a.md".into(),
            id: "gone".into(),
            why: "x".into(),
        });
        let mut repo = clean_repo();
        repo.docs.insert("docs/a.md".into(), "no markers".into());
        let errs = manifest_errors(&m, &repo);
        assert_eq!(errs.len(), 5, "{errs:#?}");
    }

    #[test]
    fn export_text_is_what_the_boundary_checks() {
        let mut m = manifest_clean();
        m.gate_rows.push(super::super::IdGroup {
            wp: "WP-43".into(),
            ids: vec!["C-secret".into()],
        });
        let gates = "(\n    rows: [\n        (id: \"I1\", x: 1),\n        (id: \"C-secret\", x: \"forge_secret\"),\n    ],\n)\n";
        let t = export_text(&m, GATES_FILE, gates.as_bytes()).unwrap_or_default();
        assert!(!t.contains("forge_secret") && t.contains("I1"));
        assert!(export_text(&m, "a.bin", &[0xff, 0xfe, 0x00]).is_none());
        assert!(!is_code_checked(&m, "docs/a.md") && !is_code_checked(&m, STATUS_FILE));
        assert!(!is_code_checked(&m, "crates/forge-secret/src/lib.rs"));
        assert!(is_code_checked(&m, "crates/forge-base/src/lib.rs"));
    }

    #[test]
    fn positive_control_a_lost_manifest_fails_while_debt_remains() {
        assert!(no_manifest(false, 0).is_ok());
        for (file, ceiling) in [(true, 0), (false, 3), (true, 3)] {
            let err = no_manifest(file, ceiling)
                .err()
                .map(|e| e.to_string())
                .unwrap_or_default();
            assert!(
                err.contains("the manifest was lost"),
                "{file} {ceiling}: {err}"
            );
        }
    }

    #[test]
    // The ceiling reached zero (WP-44), so the comparison is always true today; it stays to
    // catch a raise.
    #[allow(clippy::absurd_extreme_comparisons)]
    fn the_ceiling_never_exceeds_the_wp41_baseline() {
        const { assert!(DEBT_CEILING <= DEBT_AT_WP41) };
    }

    #[test]
    fn the_repository_holds_the_boundary() {
        let root = crate::util::workspace_root();
        let out = run(&root, false).unwrap_or_else(|e| panic!("{e}"));
        assert!(out.starts_with("premium-boundary:"), "{out}");
        // Positive control on the real repository: one base crate gaining a premium
        // dev-dependency that the debt does not list fails, alone, naming the edge.
        let Some(m) = Manifest::load(&root).unwrap_or_else(|e| panic!("{e}")) else {
            return; // the public edition
        };
        let mut repo = load_repo(&root, &m).unwrap_or_else(|e| panic!("{e}"));
        let debt = load_debt(&root)
            .unwrap_or_else(|e| panic!("{e}"))
            .unwrap_or_default();
        assert!(check(&m, &debt, &repo, DEBT_CEILING).is_empty());
        let premium = m.crates[0].name.clone();
        let base = repo
            .members
            .iter_mut()
            .find(|x| x.name == "forge-num")
            .unwrap_or_else(|| panic!("forge-num is a member"));
        base.deps.push((premium.clone(), Kind::Dev));
        let errs = check(&m, &debt, &repo, DEBT_CEILING);
        assert!(
            errs.len() == 1
                && errs[0].contains(&format!("forge-num depends on premium crate {premium}")),
            "{errs:#?}"
        );
    }
}
