//! How a Forge revision is laid out in Git (ADR 0035; Ch.33.2's three classes).
//!
//! **One Forge revision is one commit on `refs/heads/main`**, and the commit is a pure
//! function of the revision, so every replica of a project names it with the same Git id:
//!
//! | In the commit's tree | What |
//! |---|---|
//! | `<path>` | every **text** project file (UTF-8, no NUL, at most [`TEXT_MAX`]) at its own path: scenes, settings, sidecars — diffable and reviewable in a pull request |
//! | `.forge/revision.ron` | the revision record ([`forge_store::kit::RevRecord`]): its id is the id every backend gives it |
//! | `.forge/tree` | the Forge tree (`<blake3> <path>` per file): which files the revision has, binary ones included |
//! | `.forge/commands.jsonl` | the command log: the real history (Ch.33.4) |
//! | `.gitignore` | generated ignore rules (Ch.33.5): the store's own data and every binary path, so nobody commits bytes the store keeps elsewhere and nobody hand-writes one |
//!
//! **Binary files are engine-native blobs, not tree entries** — "LFS semantics, but engine
//! native" (Ch.33.2): their bytes are Git blobs reachable from a second ref,
//! `refs/forge/blobs`, one commit per revision that brought new ones (a tree of
//! `<blake3 hex>` entries). A plain `git clone` (which fetches branches only) and every
//! pull-request diff never download or show them; a Forge clone fetches both refs.
//! **Generated content is not stored at all**: it has a `SeedPath` (Ch.4); import artefacts
//! a store is handed with `blob_put` stay in the local repository and are never pushed —
//! they are derivable, and the asset system re-derives what it misses.
//!
//! A commit's author and time come from the revision (its first issuer, `at_ms`), never from
//! the machine: the same history replayed anywhere is the same Git history.

use std::collections::BTreeMap;

use forge_store::kit::RevRecord;
use forge_store::{Blake3, StoreError, StorePath};
use gix::ObjectId;

use super::repo::Repo;

/// The branch holding one commit per Forge revision.
pub(crate) const MAIN_REF: &str = "refs/heads/main";
/// The chain of commits whose trees hold the binary blobs.
pub(crate) const BLOBS_REF: &str = "refs/forge/blobs";
/// The metadata directory in a revision's tree (a project path can never be under it).
pub(crate) const META: &str = ".forge";
pub(crate) const RECORD: &str = "revision.ron";
pub(crate) const FORGE_TREE: &str = "tree";
pub(crate) const LOG: &str = "commands.jsonl";
pub(crate) const IGNORE: &str = ".gitignore";
/// A file larger than this is a binary blob even when it is text (a Git host diffs and
/// renders text; a 50 MB generated table is not something to review line by line).
pub(crate) const TEXT_MAX: usize = 1 << 20;

/// Whether `bytes` are stored as a text file in the tree (a function of the bytes alone).
pub(crate) fn is_text(bytes: &[u8]) -> bool {
    bytes.len() <= TEXT_MAX && !bytes.contains(&0) && std::str::from_utf8(bytes).is_ok()
}

/// Whether Git hosts accept `path` as a tree entry: `git fsck` (which GitHub, GitLab and
/// Gitea run on every push) refuses a `.git` segment and its NTFS short name.
pub(crate) fn git_safe(path: &StorePath) -> bool {
    path.segments().all(|s| {
        let l = s.to_ascii_lowercase();
        l != ".git" && !l.starts_with("git~")
    })
}

/// The generated ignore rules for a revision whose binary (not-in-tree) paths are `binary`.
pub(crate) fn ignore_rules(binary: &[&StorePath]) -> String {
    let mut out = String::from(
        "# Generated by Forge's Git store (Ch.33.2, Ch.33.5); every save rewrites it.\n\
         # The store's own data in a project folder:\n\
         /.forge/\n",
    );
    if !binary.is_empty() {
        out.push_str(
            "# Binary files: their bytes are engine-native blobs on refs/forge/blobs, not in\n\
             # this tree (a Forge clone fetches them):\n",
        );
        for p in binary {
            out.push('/');
            for c in p.as_str().chars() {
                if matches!(c, '[' | ']' | '*' | '?' | '\\') {
                    out.push('\\');
                }
                out.push(c);
            }
            out.push('\n');
        }
    }
    out
}

/// The signature a revision's commits carry.
pub(crate) fn signature(rec: &RevRecord) -> gix::actor::Signature {
    let who = rec.issuers.first().map_or("forge", String::as_str);
    let clean: String = who
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.' | ':') {
                c
            } else {
                '-'
            }
        })
        .collect();
    gix::actor::Signature {
        name: who.into(),
        email: format!("{}@forge.invalid", clean.replace(':', ".")).into(),
        time: gix::date::Time {
            seconds: i64::try_from(rec.at_ms / 1000).unwrap_or(i64::MAX),
            offset: 0,
        },
    }
}

/// A directory being assembled into Git trees.
#[derive(Default)]
struct Dir {
    files: BTreeMap<String, ObjectId>,
    dirs: BTreeMap<String, Dir>,
}

impl Dir {
    fn insert(&mut self, segments: &[&str], id: ObjectId) {
        match segments {
            [] => {}
            [file] => {
                self.files.insert((*file).to_string(), id);
            }
            [dir, rest @ ..] => self
                .dirs
                .entry((*dir).to_string())
                .or_default()
                .insert(rest, id),
        }
    }

    fn write(self, repo: &Repo) -> Result<ObjectId, StoreError> {
        let mut items: Vec<(String, bool, ObjectId)> = Vec::new();
        for (name, d) in self.dirs {
            items.push((name, true, d.write(repo)?));
        }
        for (name, id) in self.files {
            items.push((name, false, id));
        }
        repo.write_tree(items)
    }
}

/// The Git objects of one revision, ready to write.
pub(crate) struct RevisionTree<'a> {
    /// Text files in the tree: `(path, blob)`.
    pub text: Vec<(&'a StorePath, ObjectId)>,
    /// Binary (or not Git-safe) files: their paths, for the ignore rules.
    pub binary: Vec<&'a StorePath>,
    /// The project has its own `.gitignore` (it wins; no rules are generated).
    pub own_ignore: bool,
    pub record: ObjectId,
    pub forge_tree: ObjectId,
    pub log: ObjectId,
}

/// Write a revision's Git tree; its id.
pub(crate) fn write_tree(repo: &Repo, t: &RevisionTree<'_>) -> Result<ObjectId, StoreError> {
    let mut root = Dir::default();
    for (p, id) in &t.text {
        let segs: Vec<&str> = p.segments().collect();
        root.insert(&segs, *id);
    }
    root.insert(&[META, RECORD], t.record);
    root.insert(&[META, FORGE_TREE], t.forge_tree);
    root.insert(&[META, LOG], t.log);
    if !t.own_ignore {
        let rules = repo.write_blob(ignore_rules(&t.binary).as_bytes())?;
        root.insert(&[IGNORE], rules);
    }
    root.write(repo)
}

/// The commit message: the revision's message and a trailer naming its Forge id.
pub(crate) fn message(rec: &RevRecord) -> String {
    let m = rec.message.trim_end();
    let m = if m.is_empty() { "(no message)" } else { m };
    format!("{m}\n\nForge-Revision: {}\n", rec.id())
}

/// A revision commit's `.forge/` files: `(record, forge tree, log)` blob ids.
pub(crate) fn meta_of(repo: &Repo, tree: &ObjectId) -> Result<Option<[ObjectId; 3]>, StoreError> {
    let Some(meta) = repo
        .tree(tree)?
        .into_iter()
        .find(|e| e.is_tree && e.name == META)
    else {
        return Ok(None);
    };
    let items = repo.tree(&meta.id)?;
    let get = |n: &str| {
        items
            .iter()
            .find(|e| !e.is_tree && e.name == n)
            .map(|e| e.id)
    };
    Ok(match (get(RECORD), get(FORGE_TREE), get(LOG)) {
        (Some(r), Some(t), Some(l)) => Some([r, t, l]),
        _ => None,
    })
}

/// Read a revision commit's record.
pub(crate) fn record_of(repo: &Repo, commit: &ObjectId) -> Result<RevRecord, StoreError> {
    let c = repo.commit(commit)?;
    let foreign = || StoreError::Corrupt {
        what: format!("git commit {commit}"),
        why: "it was not made by Forge (it has no .forge/revision.ron): Forge reads histories \
              it wrote; importing plain-Git commits is not supported yet"
            .into(),
    };
    let [rec, _, _] = meta_of(repo, &c.tree)?.ok_or_else(foreign)?;
    let (_, bytes) = repo.read(&rec)?;
    let text = String::from_utf8(bytes).map_err(|_| foreign())?;
    ron::from_str::<RevRecord>(&text).map_err(|e| StoreError::Corrupt {
        what: format!("the revision record of git commit {commit}"),
        why: e.to_string(),
    })
}

/// Every text file's `(path, blob)` in a revision commit's tree (the `.forge/` metadata and
/// the generated `.gitignore` excluded; a project's own `.gitignore` is a file like any).
pub(crate) fn text_files(
    repo: &Repo,
    tree: &ObjectId,
) -> Result<BTreeMap<String, ObjectId>, StoreError> {
    let mut out = BTreeMap::new();
    let mut stack = vec![(String::new(), *tree)];
    while let Some((prefix, id)) = stack.pop() {
        for e in repo.tree(&id)? {
            let path = if prefix.is_empty() {
                e.name.clone()
            } else {
                format!("{prefix}/{}", e.name)
            };
            if prefix.is_empty() && e.name == META {
                continue;
            }
            if e.is_tree {
                stack.push((path, e.id));
            } else {
                out.insert(path, e.id);
            }
        }
    }
    Ok(out)
}

/// Parse a blob name on the blobs chain.
pub(crate) fn blob_name(name: &str) -> Option<Blake3> {
    name.parse().ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn text_is_decided_by_the_bytes_and_paths_git_refuses_are_found() {
        assert!(is_text(b"Scene(\r\n)\n"));
        assert!(!is_text(b"PNG\0"));
        assert!(!is_text(&[0xff, 0xfe]));
        assert!(!is_text(&vec![b'a'; TEXT_MAX + 1]));
        let p = |s: &str| StorePath::new(s).unwrap_or_else(|e| panic!("{e}"));
        assert!(git_safe(&p("scenes/main.ron")));
        assert!(!git_safe(&p("a/.GIT/config")));
        assert!(!git_safe(&p("GIT~1/x")));
        let rules = ignore_rules(&[&p("tex/[a].png")]);
        assert!(rules.contains("/.forge/\n"));
        assert!(rules.contains("/tex/\\[a\\].png\n"), "{rules}");
    }
}
